[Side nav alt] Creating side nav alt with chevrons.
healthgovau/health-design-system pull request #87
Opened 2021-12-17 03:04 UTC by adrianconte

2021-12-17 04:42 UTC, adrianconte commented
Adds 'side nav alternative' (currently used on health.gov.au.)
![image](https://user-images.githubusercontent.com/4738677/146490106-47ff706f-e08f-4b8e-8d8f-ff70b909456d.png)

2022-02-07 03:56 UTC, Benjen requested changes
There is a lot of duplication of markup here. I am sure there is a way we can reduce using some kind of extension/inclusion functionality in Handlebars. Actually I know there is a lot of similar duplication in many of the HDS components. We had planned to address this in HDS v2.x, but unfortunately that never got off the ground due to lack of resources :-(

Any idea of how difficult it would be to refactor these particular changes to make it a bit more DRY?

2022-02-07 03:56 UTC, Benjen commented on docs/components/detail/abbreviations.html
> +<div class="Status Status--unlabelled">
@adrianconte could you look at the formatting of this section and update accordingly in each of the relevant files.

2022-02-07 03:56 UTC, Benjen commented on docs/components/detail/abbreviations.html
> +
@adrianconte there is a lot of vertical spacing in here. Could you please check the formatting and update accordingly in each relevant file.

2022-02-09 05:31 UTC, merged